---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bootc-desktop
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/lazydocker
        - atim/starship
        - lihaohong/yazi
        - scottames/ghostty

      keys:
        - https://downloads.1password.com/linux/keys/1password.asc # 1password
        - https://cli.github.com/packages/githubcli-archive-keyring.asc # github cli
        - https://dl.google.com/linux/linux_signing_key.pub # google chrome
        - https://packages.microsoft.com/keys/microsoft.asc # vscode

      files:
        - 1password.repo # 1password
        - claude-code.repo # claude code
        - https://cli.github.com/packages/rpm/gh-cli.repo # github cli
        - google-chrome.repo # google chrome
        - https://kubecolor.github.io/packages/rpm/kubecolor.repo # kubecolor
        - vscode.repo # vscode

    install:
      packages:
        # GNOME additions
        - adw-gtk3-theme
        - ffmpegthumbnailer
        - gnome-tweaks

        # Development tools
        - cargo
        - claude-code
        - code
        - git-delta
        - git-lfs
        - golang
        - kubecolor
        - kubernetes1.33-client
        - make
        - nodejs
        - nodejs-npm
        - rust
        - rust-src

        # Terminal and shells
        - fish
        - ghostty
        - starship
        - zsh-autosuggestions
        - zsh-syntax-highlighting

        # CLI tools and tui apps
        - awscli2
        - bat
        - btop
        - du-dust
        - eza
        - fastfetch
        - fd-find
        - fzf
        - gh
        - lazydocker
        - neovim
        - ripgrep
        - wl-clipboard
        - yazi
        - yq
        - zoxide

        # Containers and virtualization
        - distrobox
        - podman-compose
        - podman-docker

        # Browsers
        - google-chrome-stable

        # Gaming
        - https://discord.com/api/download?platform=linux&format=rpm # discord
        - mangohud
        - steam

        # Misc utilities
        - 1password
        - cabextract
        - chezmoi
        - nextcloud-client
        - restic
        - tailscale
        - unrar

    remove:
      packages:
        - toolbox

  - type: brew
    nofile-limits: true
    brew-analytics: false
    auto-update: true
    update-interval: 1d
    update-wait-after-boot: 5m
    auto-upgrade: true
    upgrade-interval: 1d
    upgrade-wait-after-boot: 10m

  - type: fonts
    fonts:
      nerd-fonts:
        - AdwaitaMono
        - FiraCode
        - FiraMono
        - Hack
        - Meslo
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        - Inter

  - type: script
    snippets:
      - "ln -sf /usr/bin/podman-compose /usr/bin/docker-compose"
    scripts:
      - install-low-latency-layer.sh
      - install-ms-fonts.sh

  - type: gnome-extensions
    install:
      - App Hider
      - AppIndicator and KStatusNotifierItem Support
      - Caffeine
      - Dash to Dock
      - Just Perfection
      - In Picture
      - Night Theme Switcher

  - type: gschema-overrides
    include:
      - desktop.gschema.override
      - extensions.gschema.override

  - type: systemd
    system:
      enabled:
        - tailscaled.service
    user:
      enabled:
        - podman.socket

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          # Added applications
          - com.dec05eba.gpu_screen_recorder
          - com.getpostman.Postman
          - com.github.marhkb.Pods
          - com.github.mtkennerly.ludusavi
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - com.slack.Slack
          - com.spotify.Client
          - dev.qwery.AddWater
          - io.github.Foldex.AdwSteamGtk
          - io.github.celluloid_player.Celluloid
          - io.github.realmazharhussain.GdmSettings
          - it.mijorus.gearlever
          - md.obsidian.Obsidian
          - org.libreoffice.LibreOffice
          - org.signal.Signal
          - us.zoom.Zoom

          # Added runtimes
          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark

          # Gnome applications
          - org.gnome.Boxes
          - org.gnome.Loupe
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.Connections
          - org.gnome.Contacts
          - org.gnome.Extensions
          - org.gnome.Logs
          - org.gnome.Loupe
          - org.gnome.Maps
          - org.gnome.NautilusPreviewer
          - org.gnome.Papers
          - org.gnome.Snapshot
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gnome.World.PikaBackup
          - org.gnome.baobab
          - org.gnome.clocks
          - org.gnome.font-viewer

  - type: signing
