---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bootc-desktop
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/lazydocker
        - atim/starship
        - lihaohong/yazi
        - scottames/ghostty
      keys:
        - https://cli.github.com/packages/githubcli-archive-keyring.asc # github cli

      files:
        - https://cli.github.com/packages/rpm/gh-cli.repo # github cli
        - https://kubecolor.github.io/packages/rpm/kubecolor.repo # kubecolor

    install:
      packages:
        - adw-gtk3-theme
        - awscli2
        - bat
        - btop
        - cabextract
        - cargo
        - distrobox
        - du-dust
        - eza
        - fastfetch
        - fd-find
        - ffmpegthumbnailer
        - fish
        - fzf
        - git-delta
        - gnome-tweaks
        - golang
        - helix
        - kubernetes1.33-client
        - make
        - nodejs
        - nodejs-npm
        - podman-compose
        - podman-docker
        - ripgrep
        - rust
        - rust-src
        - tailscale
        - unrar
        - wl-clipboard
        - yq
        - zoxide
        - zsh-autosuggestions
        - zsh-syntax-highlighting

        # copr + custom repos
        - gh
        - ghostty
        - lazydocker
        - kubecolor
        - starship
        - yazi

        # rpmfusion
        # - intel-media-driver
        #- libheif-freeworld
        # - mesa-va-drivers-freeworld
        # - mesa-va-drivers-freeworld.i686
        # - pipewire-codec-aptx

    remove:
      packages:
        - toolbox
        - firefox
        - firefox-langpacks

    # replace:
    #   - from-repo: fedora-multimedia
    #     allow-erasing: true
    #     packages:
    #       - old: ffmpeg-free
    #         new: ffmpeg

    # group-install:
    #   install-weak-deps: false
    #   exclude:
    #     - PackageKit-gstreamer-plugin
    #   packages:
    #     - multimedia

  - type: fonts
    fonts:
      nerd-fonts:
        - AdwaitaMono
        - FiraCode
        - FiraMono
        - Hack
        - Meslo
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        - Inter

  - type: script
    snippets:
      - "ln -sf /usr/bin/podman-compose /usr/bin/docker-compose"
    scripts:
      - install-ms-fonts.sh

  - type: gnome-extensions
    install:
      - App Hider
      - AppIndicator and KStatusNotifierItem Support
      - Caffeine
      - Dash to Dock
      - Just Perfection
      - In Picture
      - Night Theme Switcher

  - type: gschema-overrides
    include:
      - desktop.gschema.override
      - extensions.gschema.override

  - type: systemd
    system:
      enabled:
        - tailscaled.service
    user:
      enabled:
        - podman.socket

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        install:
          # Added applications
          - com.dec05eba.gpu_screen_recorder
          #- com.discordapp.Discord
          - com.getpostman.Postman
          - com.github.marhkb.Pods
          - com.github.mtkennerly.ludusavi
          - com.github.tchx84.Flatseal
          #- com.google.Chrome
          - com.mattjakeman.ExtensionManager
          - com.nextcloud.desktopclient.nextcloud
          #- com.onepassword.OnePassword
          - com.slack.Slack
          - com.spotify.Client
          #- com.valvesoftware.Steam
          #- com.visualstudio.code
          - dev.qwery.AddWater
          - io.github.Foldex.AdwSteamGtk
          - io.github.celluloid_player.Celluloid
          - io.github.realmazharhussain.GdmSettings
          - it.mijorus.gearlever
          - md.obsidian.Obsidian
          - org.libreoffice.LibreOffice
          #- org.mozilla.firefox
          - org.signal.Signal
          - us.zoom.Zoom

          # Added runtimes
          - com.visualstudio.code.tool.podman
          - org.freedesktop.Platform.ffmpeg-full
          - org.freedesktop.Sdk.Extension.golang
          - org.freedesktop.Sdk.Extension.node24
          - org.freedesktop.Sdk.Extension.rust-stable
          - org.freedesktop.Sdk.Extension.typescript
          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark

          # Gnome applications
          - org.gnome.Boxes
          - org.gnome.Loupe
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.Connections
          - org.gnome.Contacts
          - org.gnome.Extensions
          - org.gnome.Logs
          - org.gnome.Loupe
          - org.gnome.Maps
          - org.gnome.NautilusPreviewer
          - org.gnome.Papers
          - org.gnome.Platform
          - org.gnome.Platform
          - org.gnome.Snapshot
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gnome.World.PikaBackup
          - org.gnome.baobab
          - org.gnome.clocks
          - org.gnome.font-viewer

  - type: dnf
    repos:
      keys:
        - https://downloads.1password.com/linux/keys/1password.asc # 1password
        - https://dl.google.com/linux/linux_signing_key.pub # google chrome
        - https://packages.microsoft.com/keys/microsoft.asc # vscode
      files:
        - 1password.repo # 1password
        - google-chrome.repo # google chrome
        - vscode.repo # vscode

    install:
      packages:
        - 1password
        - code
        - https://discord.com/api/download?platform=linux&format=rpm # discord
        - firefox
        - firefox-langpacks
        - google-chrome-stable
        - steam

  - type: signing
